// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPPjNmGudSSaSMdTZtxGaLFrYcg_7M8I',
    appId: '1:363131369828:web:465e7391e7b2efe5cde271',
    messagingSenderId: '363131369828',
    projectId: 'fir-5-8a9d5',
    authDomain: 'fir-5-8a9d5.firebaseapp.com',
    storageBucket: 'fir-5-8a9d5.appspot.com',
    measurementId: 'G-6LF8M75B16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY8ic8AEoMKqU1Z8aomLynZKsy_ecYp-c',
    appId: '1:363131369828:android:9864de2a291daae7cde271',
    messagingSenderId: '363131369828',
    projectId: 'fir-5-8a9d5',
    storageBucket: 'fir-5-8a9d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpBfmXXpdwQgLHVni8P21qS0diwLf5-s',
    appId: '1:363131369828:ios:d259b647fcb5fb9bcde271',
    messagingSenderId: '363131369828',
    projectId: 'fir-5-8a9d5',
    storageBucket: 'fir-5-8a9d5.appspot.com',
    androidClientId: '363131369828-81c7nme9jvqbh31sfkratlnjjf9l6hn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appcrewTest',
  );
}
